### ISSUE TITLE
add support for 611 [coin]

### ISSUE THREAD

**Issue by 611project** [subnetsRU/blockchain#1]
Can you please add support for 611 [coin] to your project?
https://github.com/611project
https://611project.org

Any hint how to run the whois service using docker?

**Comment by subnetsRU** [comment]
As I can see it a copy of namecoin DNS. So why not. In later releases I can add support for 611.to.
But first I need to finish full emercoin domain support. 

We dont use docker, so cant say anything about it. I can say that it can be run with tcp-based server. 
See bird-lg about as example: https://raw.githubusercontent.com/subnetsRU/bird-lg/master/ABOUT
You can use the same method to run whois service.

**Comment by subnetsRU** [comment]
Support added.
# whois -h whois.bitname.ru pxc.611.to

% This is the Namecoin and Emercoin blockchain query service version 0.3.0 (c) bitname.ru

% Information related to pxc.611.to

domain:           pxc.611.to
name:             d/pxc
expires in:       64426 blocks
status:           registered
address:          N5FdpxX1biqMZ2JqJGacrerY4Jp3LseBGW
txid:             99e9cea9961df75083551facd23242d66e035e116b99845226626835f33af34a

last update on:   2018-01-22T23:08:40Z

% This query was served in 0.004 sec

# dig @dns.bitname.ru pxc.611.to +short
51.255.51.50

**Comment by 611project** [comment]
Awesome. Thank you!
Would you mind adding the vhost whois.611.to to whois.bitname.ru?
How do you trigger whois.php on the whois port? Using xinetd?
